name: Deploy to my server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Debian 12, same server as the deployment goes to

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Add Linux target
      run: rustup target add x86_64-unknown-linux-gnu

    - name: Build the project
      run: cargo build --target x86_64-unknown-linux-gnu --release

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Create SSH key for authentication
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Set up known hosts to avoid confirmation prompt
        ssh-keyscan 192.168.178.31 >> ~/.ssh/known_hosts

        # Deploy the binary to the server
        scp -i ~/.ssh/id_rsa target/x86_64-unknown-linux-gnu/release/todo marc@192.168.178.31:/usr/local/bin/todo